"""the export files a measurement under the layout it was taken with.

the model registry reads eval/results/export.json as a benchmark source, so a
row filed under the wrong layout is a wrong fact about a model rather than a
cosmetic slip. which layouts exist is spec/layouts, and a layout added there
has to be recognised without the export script being told about it.
"""

import json
import os
import sys

SCRIPTS = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "..", "..", "scripts")
sys.path.insert(0, SCRIPTS)

import export_results  # noqa: E402

ROW = {"model": "newcomer-4b:Q8_0", "option_mass": 0.99, "correct": "3/3", "usable": True}


def exported_layouts(tmp_path, monkeypatch, names):
    """the layout each `mass-newcomer-4b-<name>.json` is exported under."""
    (tmp_path / "layouts").mkdir()
    for name in names:
        (tmp_path / "layouts" / f"mass-newcomer-4b-{name}.json").write_text(json.dumps([ROW]))
    monkeypatch.setattr(export_results, "RESULTS", str(tmp_path))
    monkeypatch.setattr(export_results, "ROOT", str(tmp_path))
    return {os.path.basename(r["path"]): r["variant"]["layout"]
            for r in export_results.option_mass_rows()}


def test_every_layout_in_the_spec_is_exported_under_its_own_name(tmp_path, monkeypatch):
    names = ["chat", *export_results.layout_names()]
    assert exported_layouts(tmp_path, monkeypatch, names) == {
        f"mass-newcomer-4b-{name}.json": name for name in names}


def test_a_layout_added_to_the_spec_needs_no_change_to_the_export(tmp_path, monkeypatch):
    monkeypatch.setattr(export_results, "layout_names", lambda: ["newcomer-plain"])
    assert exported_layouts(tmp_path, monkeypatch, ["newcomer-plain"]) == {
        "mass-newcomer-4b-newcomer-plain.json": "newcomer-plain"}


def answered(confidence, correct):
    return {"probs": {"a": confidence, "b": 1 - confidence}, "correct": correct}


def test_calibration_says_how_far_confidence_sits_from_accuracy_and_whether_it_ranks():
    rows = [answered(0.95, True), answered(0.95, True), answered(0.95, False),
            answered(0.55, False)]
    assert export_results.calibration(rows) == {
        "ece": 0.35, "mean_confidence": 0.85, "overconfidence": 0.35,
        "confident_share": 0.75, "confident_accuracy": 0.6667, "confidence_auroc": 0.75}


def test_confidence_cannot_rank_answers_that_are_all_right_or_all_wrong():
    measured = export_results.calibration([answered(0.6, True), answered(0.7, True)])
    assert measured["confidence_auroc"] is None
    assert (measured["confident_share"], measured["confident_accuracy"]) == (0.0, None)


def test_the_readme_carries_a_calibration_table_beside_the_models_one(tmp_path, monkeypatch):
    readme = tmp_path / "README.md"
    readme.write_text("intro\n" + "".join(
        f"<!-- {name}:start (generated by make export) -->\nstale\n<!-- {name}:end -->\nprose\n"
        for name in ("models", "calibration")))
    monkeypatch.setattr(export_results, "README", str(readme))
    metrics = {"accuracy": 0.5, "correct": 2, "n": 4, "accuracy_hard": 0.25, "hard_ece": 0.2,
               "latency_p50_s": 0.5, **export_results.calibration(
                   [answered(0.95, True), answered(0.95, True), answered(0.95, False),
                    answered(0.55, False)])}
    export_results.update_readme([{
        "model": "newcomer-4b:Q8_0", "suite": "jevbench-public", "measured_utc": "2026",
        "variant": {"layout": "chat", "order_averaging": 1, "prior_correction": False,
                    "long_lists": "refuse"}, "metrics": metrics}])
    text = readme.read_text()
    assert "stale" not in text and text.count("prose") == 2
    calibration = text.split("<!-- calibration:start")[1].split("<!-- calibration:end")[0]
    assert "| newcomer-4b:Q8_0 | chat | 0.500 | 0.850 | +0.350 |" in calibration
    assert "| 75% | **0.667** | **0.750** |" in calibration


def test_a_file_that_names_no_layout_is_a_chat_reading_and_meta_is_the_registry():
    assert [export_results.mass_layout(name) for name in (
        "mass-deciders-meta.json", "mass-deciders-chat.json", "option-mass-survey.json",
        "mass-newcomer-4b-unheard-of.json")] == ["registry", "chat", "chat", "chat"]
